export { default as Home } from "./home";
export { default as PlantCare } from "./plant-care";
export { default as Blogs } from "./blogs";
export { default as ProductDetail } from "./product-details";
export { default as NotFound } from "./not-found";
export { default as Error } from "./error";
export { default as Checkout } from "./checkout";
export { default as Profile } from "./profile";
export { default as TrackOrder } from './profile/track-order'